CREATE_TABLE_USERS_DATA = """
  CREATE TABLE IF NOT EXISTS {table_name}
  (
    UserID INTEGER PRIMARY KEY,
    CardNumber INTEGER UNIQUE NOT NULL,
    PinCode INTEGER NOT NULL,
    Balance INTEGER NOT NULL,
    IsBlocked BOOLEAN DEFAULT FALSE
  );
"""
